name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: windows-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
      - run: echo "$(echo hello_world.txt)"
